// lib/valuation/industry-multiples.ts
// Industry EBITDA multiples - the ceiling multiple a business in each sector can command
// when it is fully systemised and transferable. Sourced from the Empire Worksheet industry
// reference table (204 sectors). These are indicative benchmarks, not guarantees - a real
// sale multiple depends on the specific business (see model.ts).

export interface IndustryMultiple {
  name: string;
  /** Indicative full EBITDA/earnings multiple for a systemised, transferable business. */
  multiple: number;
}

export const INDUSTRY_MULTIPLES: IndustryMultiple[] = [
  { name: 'Accounting & Tax Preparation', multiple: 8.16 },
  { name: 'Advanced Medical Equipment & Technology', multiple: 8.16 },
  { name: 'Adventure Sports Facilities & Ski Resorts', multiple: 7.57 },
  { name: 'Advertising & Marketing', multiple: 12.58 },
  { name: 'Aerospace & Defence', multiple: 10.3 },
  { name: 'Agricultural Biotechnology', multiple: 10.36 },
  { name: 'Agricultural Chemicals', multiple: 9.81 },
  { name: 'Agricultural Consultancy Services', multiple: 12.09 },
  { name: 'Agriculture Support Services', multiple: 7.08 },
  { name: 'Airlines', multiple: 20.56 },
  { name: 'Airport Operators & Services', multiple: 16.03 },
  { name: 'Aluminium', multiple: 15.54 },
  { name: 'Amusement Parks and Zoos', multiple: 8.76 },
  { name: 'Animal Breeding', multiple: 8.46 },
  { name: 'Animal Feed', multiple: 9.66 },
  { name: 'Apparel & Accessories', multiple: 8.46 },
  { name: 'Apparel & Accessories Retailers', multiple: 8.46 },
  { name: 'Appliances, Tools & Housewares', multiple: 10.03 },
  { name: 'Aquaculture', multiple: 9.73 },
  { name: 'Auto & Truck Manufacturers', multiple: 9.73 },
  { name: 'Auto Vehicles, Parts & Service Retailers', multiple: 15.17 },
  { name: 'Auto, Truck & Motorcycle Parts', multiple: 9.73 },
  { name: 'Banks*', multiple: 9.73 },
  { name: 'Beer, Wine & Liquor Stores', multiple: 9.73 },
  { name: 'Biotechnology & Medical Research', multiple: 9.29 },
  { name: 'Brewers', multiple: 9.73 },
  { name: 'Broadcasting**', multiple: 9.73 },
  { name: 'Business Support Services**', multiple: 9.73 },
  { name: 'Business Support Supplies', multiple: 9.73 },
  { name: 'Cable Service Providers', multiple: 9.73 },
  { name: 'Call Centre Services', multiple: 9.73 },
  { name: 'Casinos & Gaming', multiple: 9.29 },
  { name: 'Cattle Farming', multiple: 9.29 },
  { name: 'Child Care & Family Services', multiple: 9.29 },
  { name: 'Cleaning Services', multiple: 9.73 },
  { name: 'Closed End Funds', multiple: 9.73 },
  { name: 'Coal', multiple: 9.73 },
  { name: 'Coffee, Tea & Cocoa Farming', multiple: 9.73 },
  { name: 'Commercial Educational Services', multiple: 9.73 },
  { name: 'Commercial Fishing', multiple: 9.73 },
  { name: 'Commercial Nurseries', multiple: 9.29 },
  { name: 'Commercial Printing Services', multiple: 9.29 },
  { name: 'Commercial REITs', multiple: 12.39 },
  { name: 'Commodity Chemicals', multiple: 20.14 },
  { name: 'Communications & Networking', multiple: 4.53 },
  { name: 'Computer & Electronics Retailers', multiple: 10.07 },
  { name: 'Computer Hardware', multiple: 23.06 },
  { name: 'Construction & Engineering', multiple: 9.6 },
  { name: 'Construction Materials', multiple: 14.18 },
  { name: 'Construction Supplies & Fixtures', multiple: 10.3 },
  { name: 'Consumer Goods Rental', multiple: 11.76 },
  { name: 'Consumer Lending*', multiple: 8.22 },
  { name: 'Consumer Publishing', multiple: 10.75 },
  { name: 'Consumer Repair Services', multiple: 8.55 },
  { name: 'Content & Site Management Services', multiple: 20.56 },
  { name: 'Corporate Accounting Services', multiple: 10.07 },
  { name: 'Corporate Financial Services*', multiple: 20.56 },
  { name: 'Courier, Postal, Air Freight & Land-based Logistics', multiple: 10.47 },
  { name: 'Data Processing Services', multiple: 11.22 },
  { name: 'Department Stores', multiple: 10.9 },
  { name: 'Discount Stores', multiple: 15.54 },
  { name: 'Distillers & Wineries', multiple: 8.19 },
  { name: 'Diversi˜ed Chemicals', multiple: 9.69 },
  { name: 'Diversi˜ed Industrial Goods Wholesalers', multiple: 20.14 },
  { name: 'Diversi˜ed Investment Services', multiple: 7.57 },
  { name: 'Diversi˜ed Mining', multiple: 23.06 },
  { name: 'Diversi˜ed REITs', multiple: 10.3 },
  { name: 'Drug Retailers', multiple: 12.58 },
  { name: 'E-commerce & Marketplace Services', multiple: 10.36 },
  { name: 'Electric Utilities', multiple: 20.14 },
  { name: 'Electrical Components & Equipment', multiple: 24.35 },
  { name: 'Electronic Equipment & Parts', multiple: 13.69 },
  { name: 'Employment Services', multiple: 13.81 },
  { name: 'Entertainment Production', multiple: 13.81 },
  { name: 'Environmental Services & Equipment', multiple: 13.81 },
  { name: 'Exchange-Traded Funds', multiple: 13.81 },
  { name: 'Exhibition & Conference Services', multiple: 13.81 },
  { name: 'Financial & Commodity Market Operators & Service Providers', multiple: 13.81 },
  { name: 'Fishing & Farming Wholesale', multiple: 13.81 },
  { name: 'Fishing & Farming**', multiple: 13.81 },
  { name: 'Food Markets', multiple: 13.81 },
  { name: 'Food Processing', multiple: 13.81 },
  { name: 'Food Retail & Distribution**', multiple: 11.43 },
  { name: 'Food Wholesale', multiple: 13.81 },
  { name: 'Footwear', multiple: 13.81 },
  { name: 'Forest & Wood Products', multiple: 13.81 },
  { name: 'Funeral Services', multiple: 13.81 },
  { name: 'Fur Farming', multiple: 13.81 },
  { name: 'General Education Services', multiple: 13.81 },
  { name: 'Gold', multiple: 13.81 },
  { name: 'Golf Courses', multiple: 13.81 },
  { name: 'Grain (Crop) Production', multiple: 13.81 },
  { name: 'Ground Freight & Logistics', multiple: 13.72 },
  { name: 'Guided Tour Operators', multiple: 9.75 },
  { name: 'Gyms, Fitness and Spa Centres', multiple: 9.47 },
  { name: 'Health, Safety & Fire Protection Equipment', multiple: 9.47 },
  { name: 'Healthcare Facilities & Services', multiple: 11.43 },
  { name: 'Heavy Electrical Equipment', multiple: 9.47 },
  { name: 'Heavy Machinery & Vehicles', multiple: 9.47 },
  { name: 'Highways & Rail Tracks', multiple: 9.47 },
  { name: 'Hog & Pig Farming', multiple: 9.47 },
  { name: 'Home Furnishings', multiple: 18.84 },
  { name: 'Home Furnishings Retailers', multiple: 9.42 },
  { name: 'Home Improvement Products & Services Retailers', multiple: 11.0 },
  { name: 'Homebuilding', multiple: 8.84 },
  { name: 'Hotels, Motels & Cruise Lines', multiple: 12.0 },
  { name: 'Household Electronics', multiple: 10.36 },
  { name: 'Household Products', multiple: 12.21 },
  { name: 'Hunting & Fishing', multiple: 10.91 },
  { name: 'Independent Power Producers', multiple: 10.93 },
  { name: 'Industrial Conglomerates', multiple: 12.88 },
  { name: 'Industrial Design Services', multiple: 12.88 },
  { name: 'Industrial Equipment Rental', multiple: 9.29 },
  { name: 'Industrial Machinery & Equipment', multiple: 12.39 },
  { name: 'Insurance Funds', multiple: 12.21 },
  { name: 'Integrated Oil & Gas', multiple: 20.14 },
  { name: 'Integrated Telecommunications Services', multiple: 6.77 },
  { name: 'Internet Gaming', multiple: 7.06 },
  { name: 'Internet Security & Transactions Services', multiple: 20.56 },
  { name: 'Investment Banking & Brokerage Services*', multiple: 20.14 },
  { name: 'Investment Holding Companies', multiple: 20.14 },
  { name: 'Investment Management & Fund Operators', multiple: 5.92 },
  { name: 'Iron & Steel', multiple: 11.79 },
  { name: 'IT Services & Consulting', multiple: 13.36 },
  { name: 'Legal Services', multiple: 13.36 },
  { name: 'Leisure & Recreation**', multiple: 13.36 },
  { name: 'Life & Health Insurance', multiple: 13.36 },
  { name: 'Maintenance & Repair Services', multiple: 13.36 },
  { name: 'Managed Healthcare', multiple: 13.36 },
  { name: 'Management Consulting Services', multiple: 13.36 },
  { name: 'Marinas', multiple: 13.36 },
  { name: 'Marine Freight & Logistics', multiple: 13.36 },
  { name: 'Marine Port Services', multiple: 13.36 },
  { name: 'Medical Equipment, Supplies & Distribution', multiple: 13.36 },
  { name: 'Mining Support Services & Equipment', multiple: 13.36 },
  { name: 'Miscellaneous Specialty Retailers', multiple: 13.36 },
  { name: 'Movie Theaters & Movie Products', multiple: 13.36 },
  { name: 'Multiline Insurance & Brokers', multiple: 13.36 },
  { name: 'Multiline Utilities', multiple: 8.85 },
  { name: 'Museums & Historic Places', multiple: 7.57 },
  { name: 'Mutual Funds', multiple: 10.3 },
  { name: 'Natural Gas Utilities', multiple: 9.05 },
  { name: 'Non-Alcoholic Beverages', multiple: 12.58 },
  { name: 'Non-Gold Precious Metals & Minerals', multiple: 20.14 },
  { name: 'Non-Paper Containers & Packaging', multiple: 12.58 },
  { name: 'Of˜ce Equipment', multiple: 17.58 },
  { name: 'Of˜ce Equipment & Supplies Rental', multiple: 11.0 },
  { name: 'Of˜ce Furniture', multiple: 9.33 },
  { name: 'Of˜ce Supplies', multiple: 9.29 },
  { name: 'Of˜ce Supplies Wholesale', multiple: 9.45 },
  { name: 'Oil & Gas Drilling', multiple: 5.14 },
  { name: 'Oil & Gas Exploration and Production', multiple: 12.8 },
  { name: 'Oil & Gas Re˜ning and Marketing', multiple: 12.8 },
  { name: 'Oil & Gas Transportation Services', multiple: 9.45 },
  { name: 'Oil Related Services and Equipment', multiple: 19.63 },
  { name: 'Online Services**', multiple: 19.63 },
  { name: 'Organic Farming', multiple: 19.63 },
  { name: 'Other Broadcasting', multiple: 19.63 },
  { name: 'Other Business Support Services', multiple: 19.63 },
  { name: 'Other Business Support Supplies', multiple: 19.63 },
  { name: 'Other Fishing & Farming', multiple: 19.63 },
  { name: 'Other Food Retail & Distribution', multiple: 19.63 },
  { name: 'Other Leisure & Recreation', multiple: 9.33 },
  { name: 'Other Online Services', multiple: 9.42 },
  { name: 'Other Personal Services', multiple: 10.47 },
  { name: 'Paper Packaging', multiple: 20.14 },
  { name: 'Paper Products', multiple: 21.35 },
  { name: 'Passenger Transportation, Ground & Sea', multiple: 10.34 },
  { name: 'Pension Funds', multiple: 9.73 },
  { name: 'Personal Care Services', multiple: 9.73 },
  { name: 'Personal Legal Services', multiple: 9.73 },
  { name: 'Personal Products', multiple: 9.73 },
  { name: 'Personal Services**', multiple: 9.73 },
  { name: 'Pest Control Services', multiple: 15.17 },
  { name: 'Pharmaceuticals', multiple: 9.73 },
  { name: 'Phones & Handheld Devices', multiple: 9.73 },
  { name: 'Poultry Farming', multiple: 9.73 },
  { name: 'Professional Information Services', multiple: 14.5 },
  { name: 'Professional Sports Venues', multiple: 13.09 },
  { name: 'Property & Casualty Insurance', multiple: 25.3 },
  { name: 'Public Sport Facilities', multiple: 10.56 },
  { name: 'Radio Broadcasting', multiple: 9.45 },
  { name: 'Real Estate Rental, Development & Operations', multiple: 17.02 },
  { name: 'Real Estate Services', multiple: 13.36 },
  { name: 'Recreational Products', multiple: 13.22 },
  { name: 'Reinsurance', multiple: 11.57 },
  { name: 'Renewable Energy Equipment & Services', multiple: 11.57 },
  { name: 'Renewable Fuels', multiple: 23.06 },
  { name: 'Residential REITs', multiple: 14.99 },
  { name: 'Search Engines', multiple: 17.31 },
  { name: 'Security Services', multiple: 13.11 },
  { name: 'Sheep & Specialty Livestock Farming', multiple: 9.58 },
  { name: 'Social Media & Networking', multiple: 24.35 },
  { name: 'Sugarcane Farming', multiple: 23.06 },
  { name: 'Supermarkets & Convenience Stores', multiple: 11.48 },
  { name: 'Television Broadcasting', multiple: 7.57 },
  { name: 'Testing Laboratories', multiple: 12.58 },
  { name: 'Theatres & Performing Arts', multiple: 6.63 },
  { name: 'Tobacco Stores', multiple: 11.1 },
  { name: 'Transaction & Payment Services', multiple: 13.36 },
  { name: 'Translation & Interpretation Services', multiple: 20.14 },
  { name: 'Travel Agents', multiple: 9.68 },
  { name: 'Vegetable, Fruit & Nut Farming', multiple: 12.47 },
  { name: 'Vending Machine Providers', multiple: 6.81 },
];

/** Median across all sectors - the fallback when an industry can't be matched. */
export const MEDIAN_MULTIPLE = 11.57;

const BY_NAME: Record<string, number> = Object.fromEntries(
  INDUSTRY_MULTIPLES.map((i) => [i.name.toLowerCase(), i.multiple]),
);

/**
 * Look up an industry's indicative multiple. Returns the median (with matched=false)
 * when the industry is unknown - degrade honestly, never fabricate a specific figure.
 */
export function lookupMultiple(industry: string): { multiple: number; matched: boolean } {
  if (!industry) return { multiple: MEDIAN_MULTIPLE, matched: false };
  const hit = BY_NAME[industry.trim().toLowerCase()];
  if (typeof hit === 'number') return { multiple: hit, matched: true };
  return { multiple: MEDIAN_MULTIPLE, matched: false };
}
