// lib/billing/billing.integration.test.ts
//
// The live verification the unit tests can't give: a REAL Stripe test-mode subscription, a REAL
// signed webhook payload, and the REAL Supabase adapter writing to the REAL users table.
//
// This is what proves the claims that matter and that a mock can only assert by construction:
//   - a signature generated by Stripe's own signer verifies,
//   - a checkout session really carries a 30-day trial and really demands a card,
//   - a redelivery is short-circuited by the stripe_webhook_events row,
//   - an out-of-order event really loses to users.last_stripe_event_at,
//   - a cancellation really lands as 'cancelled' with the subscription id cleared.
//
// SAFETY: it refuses to run against a live key, and it creates + deletes its own throwaway user.
// It skips (does not fail) when credentials are absent, so CI without secrets stays green.
//
// Run: npm test -- billing.integration

import { handleSubscriptionWebhook } from '@caistech/subscription-billing';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import Stripe from 'stripe';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createSubscriptionCheckoutSession } from '@caistech/subscription-billing';

import { getIdempotencyStore, getSubscriptionAdapter, TRIAL_DAYS } from './index';

const stripeKey = process.env.STRIPE_SECRET_KEY ?? '';
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY ?? '';

/**
 * The signing secret is generated here rather than read from env, and deliberately so: this test
 * both signs and verifies, so a local secret exercises Stripe's real signer against the reducer's
 * real verifier with no dependency on the deployment's secret being present (or on knowing it).
 * The production secret's job — matching what Stripe actually sends — is a deployment concern.
 */
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET || `whsec_${'v'.repeat(32)}`;

// Live keys are refused outright: this test writes rows and creates subscriptions.
const isTestMode = stripeKey.startsWith('sk_test');
const canRun = Boolean(isTestMode && supabaseUrl && serviceKey);

if (stripeKey && !isTestMode) {
  console.warn('[billing.integration] STRIPE_SECRET_KEY is not a test key — skipping (never run this live).');
}

const TEST_EMAIL = `billing-verify-${Date.now()}@example.invalid`;

describe.skipIf(!canRun)('billing integration (Stripe test mode + Supabase)', () => {
  let stripe: Stripe;
  let supabase: SupabaseClient;
  let subscription: Stripe.Subscription;
  let customerId: string;
  let productId: string;
  let userId: string;
  const eventIds: string[] = [];

  /** Build a real, Stripe-signed webhook request for an event payload. */
  function signed(type: string, object: unknown, createdSeconds: number) {
    const event = {
      id: `evt_verify_${type}_${createdSeconds}`,
      object: 'event',
      api_version: null,
      created: createdSeconds,
      type,
      data: { object },
      livemode: false,
      pending_webhooks: 0,
      request: null,
    };
    eventIds.push(event.id);
    const payload = JSON.stringify(event);
    const signature = stripe.webhooks.generateTestHeaderString({ payload, secret: webhookSecret });
    return { payload, signature };
  }

  async function deliver(type: string, object: unknown, createdSeconds: number) {
    const { payload, signature } = signed(type, object, createdSeconds);
    return handleSubscriptionWebhook(
      {
        stripe,
        webhookSecret,
        adapter: getSubscriptionAdapter(),
        idempotency: getIdempotencyStore(),
      },
      payload,
      signature,
    );
  }

  /**
   * The checkout session Stripe sends at signup. Hand-built rather than driven through a real
   * payment (a test-mode session can't complete without a card being entered in the browser) — but
   * the ids are real, so the reducer's `subscriptions.retrieve` pulls the genuine subscription and
   * derives the status from it, which is the part that matters.
   */
  function checkoutSession() {
    return {
      id: 'cs_test_verification',
      object: 'checkout.session',
      mode: 'subscription',
      customer: customerId,
      subscription: subscription.id,
      customer_details: { email: TEST_EMAIL },
      metadata: { kira_journey: 'business' },
    };
  }

  async function readUser() {
    const { data } = await supabase
      .from('users')
      .select('subscription_status, stripe_subscription_id, stripe_customer_id, last_stripe_event_at, trial_ends_at')
      .eq('id', userId)
      .single();
    return data!;
  }

  beforeAll(async () => {
    stripe = new Stripe(stripeKey, {});
    supabase = createClient(supabaseUrl, serviceKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    // A real test-mode subscription, trialing, with no payment method — the exact shape a Kira
    // signup produces on day 1.
    const product = await stripe.products.create({ name: 'Kira billing verification' });
    productId = product.id;
    const price = await stripe.prices.create({
      product: product.id,
      currency: 'aud',
      unit_amount: 49900,
      recurring: { interval: 'month' },
    });
    const customer = await stripe.customers.create({ email: TEST_EMAIL });
    customerId = customer.id;
    subscription = await stripe.subscriptions.create({
      customer: customer.id,
      items: [{ price: price.id }],
      trial_period_days: TRIAL_DAYS,
      trial_settings: { end_behavior: { missing_payment_method: 'cancel' } },
    });

    const { data, error } = await supabase
      .from('users')
      .insert({ email: TEST_EMAIL, first_name: 'Billing', last_name: 'Verification' })
      .select('id')
      .single();
    if (error) throw new Error(`could not create the throwaway user: ${error.message}`);
    userId = data.id;
  }, 60_000);

  afterAll(async () => {
    // Leave nothing behind — not in Stripe, not in the users table, not in the idempotency ledger.
    if (userId) await supabase.from('users').delete().eq('id', userId);
    if (eventIds.length) await supabase.from('stripe_webhook_events').delete().in('event_id', eventIds);
    if (subscription?.id) await stripe.subscriptions.cancel(subscription.id).catch(() => {});
    if (customerId) await stripe.customers.del(customerId).catch(() => {});
    if (productId) await stripe.products.update(productId, { active: false }).catch(() => {});
  }, 60_000);

  it('creates a checkout session with a 30-day trial that still demands a card', async () => {
    const session = await createSubscriptionCheckoutSession({
      stripe,
      lineItem: {
        currency: 'AUD',
        unitAmount: 49900,
        productName: 'Kira Business Plan — verification',
      },
      trialDays: TRIAL_DAYS,
      cardAtSignup: true,
      successUrl: 'https://kira-rho.vercel.app/onboarding',
      cancelUrl: 'https://kira-rho.vercel.app/plan',
    });

    // Read back what Stripe actually stored, not what we sent.
    const stored = await stripe.checkout.sessions.retrieve(session.id);
    expect(stored.mode).toBe('subscription');
    expect(stored.payment_method_collection).toBe('always');
    expect(stored.currency).toBe('aud');
    expect(stored.url).toBeTruthy();

    await stripe.checkout.sessions.expire(session.id).catch(() => {});
  }, 30_000);

  it('binds the account by email at checkout and records trialing (not active)', async () => {
    // The real signup sequence: at checkout the account is matched by EMAIL (it has no Stripe ids
    // yet), which is what binds the customer + subscription ids every later event matches on.
    const result = await deliver('checkout.session.completed', checkoutSession(), subscription.created);

    expect(result.status).toBe(200);
    expect(result.body.outcome).toBe('applied');

    const user = await readUser();
    // The pre-package webhook wrote a flat 'active' on day 1 of a free month. The reducer retrieves
    // the real subscription, so this is the status Stripe actually holds.
    expect(user.subscription_status).toBe('trialing');
    expect(user.stripe_subscription_id).toBe(subscription.id);
    expect(user.stripe_customer_id).toBe(customerId);
    expect(user.last_stripe_event_at).toBeTruthy();
    expect(user.trial_ends_at).toBeTruthy();
  }, 30_000);

  it('short-circuits a redelivery of the same event', async () => {
    const result = await deliver('checkout.session.completed', checkoutSession(), subscription.created);
    expect(result.body.outcome).toBe('duplicate');
  }, 30_000);

  it('ignores an out-of-order event older than the state already stored', async () => {
    // An hour-old "active" arriving after the trialing state must not win.
    const stale = { ...subscription, status: 'active' as const };
    const result = await deliver('customer.subscription.updated', stale, subscription.created - 3600);

    expect(result.body.outcome).toBe('stale');
    expect((await readUser()).subscription_status).toBe('trialing');
  }, 30_000);

  it('rejects a payload whose signature does not match', async () => {
    const { payload } = signed('customer.subscription.updated', subscription, subscription.created + 5);
    const forged = stripe.webhooks.generateTestHeaderString({ payload, secret: 'whsec_wrong_secret' });

    const result = await handleSubscriptionWebhook(
      { stripe, webhookSecret, adapter: getSubscriptionAdapter(), idempotency: getIdempotencyStore() },
      payload,
      forged,
    );

    expect(result.status).toBe(400);
    expect(result.body.outcome).toBe('signature_invalid');
  }, 30_000);

  it('lands a cancellation as cancelled and clears the subscription id', async () => {
    const cancelled = { ...subscription, status: 'canceled' as const };
    const result = await deliver('customer.subscription.deleted', cancelled, subscription.created + 60);

    expect(result.body.outcome).toBe('applied');

    const user = await readUser();
    // 'cancelled' (two Ls) is what the AppUser type and the admin panel read.
    expect(user.subscription_status).toBe('cancelled');
    // Cleared so a cancelled row can never be matched as an active subscriber again.
    expect(user.stripe_subscription_id).toBeNull();
  }, 30_000);
});
