// lib/billing/billing.integration.test.ts
//
// The live verification the unit tests can't give: a REAL Stripe test-mode subscription, a REAL
// signed webhook payload, and the REAL Supabase adapter writing to the REAL users table.
//
// This is what proves the claims that matter and that a mock can only assert by construction:
//   - a signature generated by Stripe's own signer verifies,
//   - a checkout session really carries a 30-day trial and really demands a card,
//   - a redelivery is short-circuited by the stripe_webhook_events row,
//   - an out-of-order event really loses to users.last_stripe_event_at,
//   - a cancellation really lands as 'cancelled' with the subscription id cleared.
//
// SAFETY: it refuses to run against a live key, and it creates + deletes its own throwaway user.
// It skips (does not fail) when credentials are absent, so CI without secrets stays green.
//
// Run: npm test -- billing.integration

import { handleSubscriptionWebhook } from '@caistech/subscription-billing';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import Stripe from 'stripe';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createSubscriptionCheckoutSession } from '@caistech/subscription-billing';

import { getIdempotencyStore, getSubscriptionAdapter, METER_EVENT_NAME } from './index';

/**
 * The fixture subscription below is created `trialing` on purpose — it exists to prove the reducer
 * normalizes Stripe's `trialing` rather than flattening it to `active`. It is NOT Kira's commercial
 * model: Kira bills in arrears and issues no trials (see ./arrears.ts and the checkout test).
 */
const FIXTURE_TRIAL_DAYS = 30;

const stripeKey = process.env.STRIPE_SECRET_KEY ?? '';
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
const serviceKey = process.env.SUPABASE_SECRET_KEY ?? '';

/**
 * The signing secret is generated here rather than read from env, and deliberately so: this test
 * both signs and verifies, so a local secret exercises Stripe's real signer against the reducer's
 * real verifier with no dependency on the deployment's secret being present (or on knowing it).
 * The production secret's job — matching what Stripe actually sends — is a deployment concern.
 */
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET || `whsec_${'v'.repeat(32)}`;

// Live keys are refused outright: this test writes rows and creates subscriptions.
const isTestMode = stripeKey.startsWith('sk_test');
const canRun = Boolean(isTestMode && supabaseUrl && serviceKey);

if (stripeKey && !isTestMode) {
  console.warn('[billing.integration] STRIPE_SECRET_KEY is not a test key — skipping (never run this live).');
}

const TEST_EMAIL = `billing-verify-${Date.now()}@example.invalid`;

describe.skipIf(!canRun)('billing integration (Stripe test mode + Supabase)', () => {
  let stripe: Stripe;
  let supabase: SupabaseClient;
  let subscription: Stripe.Subscription;
  let customerId: string;
  let productId: string;
  let userId: string;
  const eventIds: string[] = [];

  /**
   * The clock this test's synthetic events are stamped with — deliberately a day ahead of the
   * subscription it describes, which is the fix for a race that made this file fail only when the
   * whole suite ran.
   *
   * We are not the only writer. Creating a subscription in the shared Stripe TEST account makes
   * Stripe deliver `customer.subscription.created` to the registered endpoint — the DEPLOYED app —
   * which resolves the customer's email, finds the row we just inserted, and applies it against the
   * SAME Supabase this test reads. Its event is stamped a second after `subscription.created`, so
   * our `checkout.session.completed` stamped AT `subscription.created` was genuinely older and the
   * out-of-order guard correctly rejected it as 'stale'. Running this file alone simply beat the
   * delivery; a full suite gave Stripe the extra seconds it needed. The reducer was right — the
   * test was racing production.
   *
   * A day ahead puts every event here beyond anything the real endpoint can emit for this
   * subscription, so the guard resolves in our favour whichever arrives first. Relative ordering
   * between our own events (redelivery, out-of-order, cancellation) is preserved by offsetting
   * from this base rather than from `subscription.created`.
   */
  let eventClock: number;

  /** Build a real, Stripe-signed webhook request for an event payload. */
  function signed(type: string, object: unknown, createdSeconds: number) {
    const event = {
      id: `evt_verify_${type}_${createdSeconds}`,
      object: 'event',
      api_version: null,
      created: createdSeconds,
      type,
      data: { object },
      livemode: false,
      pending_webhooks: 0,
      request: null,
    };
    eventIds.push(event.id);
    const payload = JSON.stringify(event);
    const signature = stripe.webhooks.generateTestHeaderString({ payload, secret: webhookSecret });
    return { payload, signature };
  }

  async function deliver(type: string, object: unknown, createdSeconds: number) {
    const { payload, signature } = signed(type, object, createdSeconds);
    return handleSubscriptionWebhook(
      {
        stripe,
        webhookSecret,
        adapter: getSubscriptionAdapter(),
        idempotency: getIdempotencyStore(),
      },
      payload,
      signature,
    );
  }

  /**
   * The checkout session Stripe sends at signup. Hand-built rather than driven through a real
   * payment (a test-mode session can't complete without a card being entered in the browser) — but
   * the ids are real, so the reducer's `subscriptions.retrieve` pulls the genuine subscription and
   * derives the status from it, which is the part that matters.
   */
  function checkoutSession() {
    return {
      id: 'cs_test_verification',
      object: 'checkout.session',
      mode: 'subscription',
      customer: customerId,
      subscription: subscription.id,
      customer_details: { email: TEST_EMAIL },
      metadata: { kira_journey: 'business' },
    };
  }

  async function readUser() {
    const { data } = await supabase
      .from('users')
      .select('subscription_status, stripe_subscription_id, stripe_customer_id, last_stripe_event_at, trial_ends_at')
      .eq('id', userId)
      .single();
    return data!;
  }

  beforeAll(async () => {
    stripe = new Stripe(stripeKey, {});
    supabase = createClient(supabaseUrl, serviceKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    // A real test-mode subscription, trialing, with no payment method — the exact shape a Kira
    // signup produces on day 1.
    const product = await stripe.products.create({ name: 'Kira billing verification' });
    productId = product.id;
    const price = await stripe.prices.create({
      product: product.id,
      currency: 'aud',
      unit_amount: 49900,
      recurring: { interval: 'month' },
    });
    const customer = await stripe.customers.create({ email: TEST_EMAIL });
    customerId = customer.id;
    subscription = await stripe.subscriptions.create({
      customer: customer.id,
      items: [{ price: price.id }],
      trial_period_days: FIXTURE_TRIAL_DAYS,
      trial_settings: { end_behavior: { missing_payment_method: 'cancel' } },
    });
    eventClock = subscription.created + 86_400;

    const { data, error } = await supabase
      .from('users')
      .insert({ email: TEST_EMAIL, first_name: 'Billing', last_name: 'Verification' })
      .select('id')
      .single();
    if (error) throw new Error(`could not create the throwaway user: ${error.message}`);
    userId = data.id;
  }, 60_000);

  afterAll(async () => {
    // Leave nothing behind — not in Stripe, not in the users table, not in the idempotency ledger.
    if (userId) await supabase.from('users').delete().eq('id', userId);
    if (eventIds.length) await supabase.from('stripe_webhook_events').delete().in('event_id', eventIds);
    if (subscription?.id) await stripe.subscriptions.cancel(subscription.id).catch(() => {});
    if (customerId) await stripe.customers.del(customerId).catch(() => {});
    if (productId) await stripe.products.update(productId, { active: false }).catch(() => {});
  }, 60_000);

  it('creates an ARREARS checkout session — metered, no trial, card still demanded', async () => {
    const session = await createSubscriptionCheckoutSession({
      stripe,
      lineItem: {
        arrears: true,
        meterEventName: METER_EVENT_NAME,
        lookupKeyPrefix: 'kira-verify',
        currency: 'AUD',
        unitAmount: 49900,
        productName: 'Kira Business Plan — verification',
      },
      cardAtSignup: true,
      successUrl: 'https://kira-rho.vercel.app/onboarding',
      cancelUrl: 'https://kira-rho.vercel.app/plan',
    });

    // Read back what Stripe actually stored, not what we sent. The price being METERED is the whole
    // point: a metered subscription invoices at period CLOSE, which is what "owed but unbilled
    // until the month is up" means mechanically. A licensed price would bill in advance and every
    // other assertion here would still pass.
    const stored = await stripe.checkout.sessions.retrieve(session.id, {
      expand: ['line_items.data.price'],
    });
    expect(stored.mode).toBe('subscription');
    expect(stored.payment_method_collection).toBe('always');
    expect(stored.currency).toBe('aud');
    expect(stored.url).toBeTruthy();

    const price = stored.line_items?.data[0]?.price as Stripe.Price | undefined;
    expect(price?.recurring?.usage_type).toBe('metered');
    expect(price?.recurring?.meter).toBeTruthy();

    await stripe.checkout.sessions.expire(session.id).catch(() => {});
  }, 45_000);

  it('refuses a trial on an arrears line item rather than silently picking one', async () => {
    // The two contracts are indistinguishable for thirty days and then invert. Kira shipped the
    // trial shape for weeks without noticing, which is exactly why this throws instead of choosing.
    await expect(
      createSubscriptionCheckoutSession({
        stripe,
        lineItem: {
          arrears: true,
          meterEventName: METER_EVENT_NAME,
          lookupKeyPrefix: 'kira-verify',
          currency: 'AUD',
          unitAmount: 49900,
          productName: 'Kira Business Plan — verification',
        },
        trialDays: 30,
        successUrl: 'https://kira-rho.vercel.app/onboarding',
        cancelUrl: 'https://kira-rho.vercel.app/plan',
      }),
    ).rejects.toThrow(/trialDays cannot be combined with an arrears line item/);
  }, 15_000);

  it('binds the account by email at checkout and records trialing (not active)', async () => {
    // The real signup sequence: at checkout the account is matched by EMAIL (it has no Stripe ids
    // yet), which is what binds the customer + subscription ids every later event matches on. The
    // reset restores that precondition even when the deployed endpoint got here first (see
    // `eventClock`) — otherwise this silently becomes a match-by-subscription-id test.
    await supabase
      .from('users')
      .update({
        subscription_status: 'trial',
        stripe_customer_id: null,
        stripe_subscription_id: null,
        last_stripe_event_at: null,
      })
      .eq('id', userId);

    const result = await deliver('checkout.session.completed', checkoutSession(), eventClock);

    expect(result.status).toBe(200);
    expect(result.body.outcome).toBe('applied');

    const user = await readUser();
    // The pre-package webhook wrote a flat 'active' on day 1 of a free month. The reducer retrieves
    // the real subscription, so this is the status Stripe actually holds.
    expect(user.subscription_status).toBe('trialing');
    expect(user.stripe_subscription_id).toBe(subscription.id);
    expect(user.stripe_customer_id).toBe(customerId);
    expect(user.last_stripe_event_at).toBeTruthy();
    expect(user.trial_ends_at).toBeTruthy();
  }, 30_000);

  it('short-circuits a redelivery of the same event', async () => {
    const result = await deliver('checkout.session.completed', checkoutSession(), eventClock);
    expect(result.body.outcome).toBe('duplicate');
  }, 30_000);

  it('ignores an out-of-order event older than the state already stored', async () => {
    // An hour-old "active" arriving after the trialing state must not win.
    const stale = { ...subscription, status: 'active' as const };
    const result = await deliver('customer.subscription.updated', stale, eventClock - 3600);

    expect(result.body.outcome).toBe('stale');
    expect((await readUser()).subscription_status).toBe('trialing');
  }, 30_000);

  it('rejects a payload whose signature does not match', async () => {
    const { payload } = signed('customer.subscription.updated', subscription, eventClock + 5);
    const forged = stripe.webhooks.generateTestHeaderString({ payload, secret: 'whsec_wrong_secret' });

    const result = await handleSubscriptionWebhook(
      { stripe, webhookSecret, adapter: getSubscriptionAdapter(), idempotency: getIdempotencyStore() },
      payload,
      forged,
    );

    expect(result.status).toBe(400);
    expect(result.body.outcome).toBe('signature_invalid');
  }, 30_000);

  it('lands a cancellation as cancelled and clears the subscription id', async () => {
    const cancelled = { ...subscription, status: 'canceled' as const };
    const result = await deliver('customer.subscription.deleted', cancelled, eventClock + 60);

    expect(result.body.outcome).toBe('applied');

    const user = await readUser();
    // 'cancelled' (two Ls) is what the AppUser type and the admin panel read.
    expect(user.subscription_status).toBe('cancelled');
    // Cleared so a cancelled row can never be matched as an active subscriber again.
    expect(user.stripe_subscription_id).toBeNull();
  }, 30_000);
});
